jobs:
  build:
    name: 'Build: Docker'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Test run-in-docker.sh
      run: 'sed -i ''s/ -it / /g'' run-in-docker.sh

        ./run-in-docker.sh mvn -B clean install

        '
      shell: bash
    - continue-on-error: true
      name: Build Dockerfile
      run: docker build .
      shell: bash
    - continue-on-error: true
      name: Build modules/openapi-generator-online
      run: 'docker build modules/openapi-generator-online/ -t test

        '
      shell: bash
    - continue-on-error: true
      name: Build and test modules/openapi-generator-cli
      run: "cp docker-entrypoint.sh ./modules/openapi-generator-cli \ndocker build\
        \ modules/openapi-generator-cli/ -t cli-test\ndocker run --rm -v \"${PWD}:/local\"\
        \ cli-test generate \\\n-i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml\
        \ \\\n-g go \\\n-o /local/out/go\n"
      shell: bash
name: Docker tests
on:
  repository_dispatch:
    types: trigger-ga___docker.yaml
