env:
  GRADLE_VERSION: 8.7
jobs:
  build:
    container: gradle:jdk11
    name: Gradle tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts')
          }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Build
      run: /bin/sh gradlew build -x test
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: true
      matrix:
        sample:
        - samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8
        - samples/openapi3/client/petstore/java/jersey2-java8-special-characters
        - samples/openapi3/client/petstore/java/jersey2-java8
        - samples/client/petstore/java/jersey2-java8-localdatetime
        - samples/client/petstore/java/jersey2-java8
        - samples/client/petstore/java/okhttp-gson
        - samples/client/petstore/java/okhttp-gson-group-parameter
        - samples/client/petstore/java/webclient-swagger2
name: Gradle tests (Java samples)
on:
  repository_dispatch:
    types: trigger-ga___gradle-test.yaml
