jobs:
  build:
    name: 'Build: JDK ${{ matrix.java }} (${{ matrix.os }})'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', 'modules/**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('modules/openapi-generator-gradle-plugin/pom.xml')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: ${{ matrix.java }}
        maven-version: 3.8.8
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: Build with Maven
      run: ./mvnw clean -nsu -B --quiet -Dorg.slf4j.simpleLogger.defaultLogLevel=error
        --no-transfer-progress install --file pom.xml
      shell: bash
    - continue-on-error: true
      if: matrix.java == '11' && matrix.os == 'ubuntu-latest'
      name: Upload Maven build artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: modules/openapi-generator-cli/target/openapi-generator-cli.jar
    - continue-on-error: true
      name: Test Gradle plugin usage
      run: gradle -b modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
        buildGoSdk --stacktrace
      shell: bash
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      if: matrix.java == '11'
      name: Test Maven plugin integration
      run: 'cd modules/openapi-generator-maven-plugin

        mvn clean verify -Pintegration

        '
      shell: bash
    strategy:
      matrix:
        java:
        - 11
        - 17
        os:
        - ubuntu-latest
  verify:
    name: Verify outputs on ${{ matrix.os }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: 11
        maven-version: 3.8.8
    - continue-on-error: true
      name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact
    - continue-on-error: true
      name: Run Ensures Script
      run: 'git config --global core.fileMode false

        git config --global core.safecrlf false

        git config --global core.autocrlf true

        ./mvnw clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

        # test with java (jersey2) client generation only as ensure-up-to-date script
        is run in another job instead

        ./bin/generate-samples.sh ./bin/configs/java-jersey2-8.yaml

        # test debugSupportingFiles

        ./bin/generate-samples.sh ./bin/configs/go-petstore.yaml -- --global-property
        debugSupportingFiles

        '
      shell: bash
    strategy:
      matrix:
        os:
        - ubuntu-latest
name: Linux tests
on:
  repository_dispatch:
    types: trigger-ga___linux.yaml
