jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        cache-name: cache-maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2/repository

          ~/.gradle

          !~/.gradle/caches/*/plugin-resolution/

          !~/.m2/repository/org/openapitools/

          '
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          ${{ runner.os }}-build-

          '
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: Run maven
      run: ./mvnw clean --no-snapshot-updates --batch-mode --quiet install -DskipTests
        -Dorg.slf4j.simpleLogger.defaultLogLevel=error
    - continue-on-error: true
      run: ls -la  modules/openapi-generator-cli/target
    - continue-on-error: true
      name: Upload openapi-generator-cli.jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-generator-cli.jar
        path: modules/openapi-generator-cli/target/openapi-generator-cli.jar
        retention-days: 1
  documentation:
    name: Docs up-to-date
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Download openapi-generator-cli.jar artifact
      uses: actions/download-artifact@v4
      with:
        name: openapi-generator-cli.jar
        path: modules/openapi-generator-cli/target
    - continue-on-error: true
      name: Generate docs
      run: 'bash bin/meta-codegen.sh

        bash bin/utils/export_docs_generators.sh

        bash bin/utils/copy-to-website.sh

        bash bin/utils/export_generators_readme.sh

        '
    - continue-on-error: true
      name: Verify git status
      run: "if [[ \"$(git status --porcelain)\" != \"\" ]]; then\n  echo \"UNCOMMITTED\
        \ CHANGES ERROR\"\n  echo \"There are uncommitted changes in working tree\
        \ after execution of 'bin/ensure-up-to-date'\"\n  echo \"Perform git diff\"\
        \n  git --no-pager diff\n  echo \"Perform git status\"\n  git status\n  echo\
        \ -e \"\\nThis script runs in pull requests against the anticipated merge\
        \ commit (as if the PR was merged now).\"\n  echo \"When you see unexpected\
        \ files here, it likely means that there are newer commits in master that\
        \ you need to \"\n  echo -e \"rebase or merge into your branch.\\n\"\n  echo\
        \ \"Please run 'bin/utils/ensure-up-to-date' locally and commit changes (UNCOMMITTED\
        \ CHANGES ERROR)\"\n  exit 1\nfi\n"
  samples:
    name: Samples up-to-date
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Download openapi-generator-cli.jar artifact
      uses: actions/download-artifact@v4
      with:
        name: openapi-generator-cli.jar
        path: modules/openapi-generator-cli/target
    - continue-on-error: true
      name: Delete samples that are entirely generated
      run: 'rm -rf samples/client/petstore/csharp/generichost/net8/AllOf

        rm -rf samples/client/petstore/csharp/generichost/net8/AnyOf

        rm -rf samples/client/petstore/csharp/generichost/net8/AnyOfNoCompare

        rm -rf samples/client/petstore/csharp/generichost/net8/FormModels

        rm -rf samples/client/petstore/csharp/generichost/net8/NullReferenceTypes

        rm -rf samples/client/petstore/csharp/generichost/net8/OneOf

        rm -rf samples/client/petstore/csharp/generichost/net8/Petstore

        rm -rf samples/client/petstore/csharp/generichost/net8/SourceGeneration

        rm -rf samples/client/petstore/csharp/generichost/net8/UseDateTimeForDate


        rm -rf samples/client/petstore/csharp/generichost/standard2.0/Petstore


        rm -rf samples/client/petstore/csharp/generichost/net4.8/AllOf

        rm -rf samples/client/petstore/csharp/generichost/net4.8/AnyOf

        rm -rf samples/client/petstore/csharp/generichost/net4.8/AnyOfNoCompare

        rm -rf samples/client/petstore/csharp/generichost/net4.8/FormModels

        rm -rf samples/client/petstore/csharp/generichost/net4.8/OneOf

        rm -rf samples/client/petstore/csharp/generichost/net4.8/Petstore

        rm -rf samples/client/petstore/csharp/generichost/net4.8/UseDateTimeForDate


        rm -rf samples/client/petstore/csharp/generichost/net4.7/AllOf

        rm -rf samples/client/petstore/csharp/generichost/net4.7/AnyOf

        rm -rf samples/client/petstore/csharp/generichost/net4.7/AnyOfNoCompare

        rm -rf samples/client/petstore/csharp/generichost/net4.7/FormModels

        rm -rf samples/client/petstore/csharp/generichost/net4.7/OneOf

        rm -rf samples/client/petstore/csharp/generichost/net4.7/Petstore

        rm -rf samples/client/petstore/csharp/generichost/net4.7/UseDateTimeForDate

        '
    - continue-on-error: true
      name: Generate samples
      run: 'bash bin/generate-samples.sh

        # when a sample is deleted, you have to generate it twice for all files to
        get created

        bash bin/generate-samples.sh

        '
    - continue-on-error: true
      name: Verify git status
      run: "if [[ \"$(git status --porcelain)\" != \"\" ]]; then\n  echo \"UNCOMMITTED\
        \ CHANGES ERROR\"\n  echo \"There are uncommitted changes in working tree\
        \ after execution of 'bin/generate-samples.sh'\"\n  echo \"Perform git diff\"\
        \n  git --no-pager diff\n  echo \"Perform git status\"\n  git status\n  echo\
        \ -e \"\\nThis script runs in pull requests against the anticipated merge\
        \ commit (as if the PR was merged now).\"\n  echo \"When you see unexpected\
        \ files here, it likely means that there are newer commits in master that\
        \ you need to \"\n  echo -e \"rebase or merge into your branch.\\n\"\n  echo\
        \ \"Please run 'bin/generate-samples.sh' locally and commit changes (UNCOMMITTED\
        \ CHANGES ERROR)\"\n  exit 1\nfi\n"
  test:
    name: Unit tests
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        cache-name: cache-maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2/repository

          ~/.gradle

          !~/.gradle/caches/*/plugin-resolution/

          !~/.m2/repository/org/openapitools/

          '
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          ${{ runner.os }}-build-

          '
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: Run unit tests
      run: ./mvnw clean --no-snapshot-updates --batch-mode --quiet --fail-at-end test
        -Dorg.slf4j.simpleLogger.defaultLogLevel=error
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish unit test reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
name: OpenAPI Generator
on:
  repository_dispatch:
    types: trigger-ga___openapi-generator.yaml
