jobs:
  build:
    name: Build JAX-RS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2

          '
    - continue-on-error: true
      name: Build
      run: mvn clean package --no-transfer-progress
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/jaxrs/jersey2
        - samples/server/petstore/jaxrs/jersey2-useTags
        - samples/server/petstore/jaxrs-jersey
        - samples/server/petstore/jaxrs-spec
        - samples/server/petstore/jaxrs-spec-interface
        - samples/server/petstore/jaxrs-spec-interface-response
        - samples/server/petstore/jaxrs-jersey
        - samples/server/petstore/jaxrs-spec
        - samples/server/petstore/jaxrs-spec-interface
        - samples/server/petstore/jaxrs-spec-interface-response
        - samples/server/petstore/jaxrs-datelib-j8
        - samples/server/petstore/jaxrs-resteasy/default
        - samples/server/petstore/jaxrs-resteasy/eap
        - samples/server/petstore/jaxrs-resteasy/eap-joda
        - samples/server/petstore/jaxrs-resteasy/eap-java8
        - samples/server/petstore/jaxrs-resteasy/joda
        - samples/server/petstore/jaxrs-cxf
        - samples/server/petstore/jaxrs-cxf-annotated-base-path
        - samples/server/petstore/jaxrs-cxf-cdi
        - samples/server/petstore/jaxrs-cxf-non-spring-app
        - samples/server/petstore/jaxrs-spec-microprofile-openapi-annotations
name: Samples JAX-RS
on:
  repository_dispatch:
    types: trigger-ga___samples-jaxrs.yaml
