jobs:
  build:
    name: Build stack projects
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: latest
    - continue-on-error: true
      name: stack test
      run: stack test
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/haskell-yesod/
        - samples/server/petstore/haskell-servant/
        - samples/server/others/haskell-servant-ping/
        - samples/client/petstore/haskell-http-client/
name: Samples Haskell
on:
  repository_dispatch:
    types: trigger-ga___samples-haskell.yaml
