jobs:
  build:
    name: Build Swift samples
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5'
    - continue-on-error: true
      name: Build
      run: swift build
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          sample: samples/client/petstore/swift5/alamofireLibrary
        os:
        - macos-latest
        sample:
        - samples/client/petstore/swift5/alamofireLibrary
        - samples/client/petstore/swift5/anycodableLibrary
        - samples/client/petstore/swift5/asyncAwaitLibrary
        - samples/client/petstore/swift5/combineLibrary
        - samples/client/petstore/swift5/default
        - samples/client/petstore/swift5/deprecated
        - samples/client/petstore/swift5/frozenEnums
        - samples/client/petstore/swift5/nonPublicApi
        - samples/client/petstore/swift5/objcCompatible
        - samples/client/petstore/swift5/oneOf
        - samples/client/petstore/swift5/promisekitLibrary
        - samples/client/petstore/swift5/readonlyProperties
        - samples/client/petstore/swift5/resultLibrary
        - samples/client/petstore/swift5/rxswiftLibrary
        - samples/client/petstore/swift5/urlsessionLibrary
        - samples/client/petstore/swift5/validation
        - samples/client/petstore/swift5/x-swift-hashable
name: Samples Swift
on:
  repository_dispatch:
    types: trigger-ga___samples-swift.yaml
