jobs:
  build:
    name: Build Java Client JDK8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2

          '
    - continue-on-error: true
      name: Setup node.js
      uses: actions/setup-node@v4
    - continue-on-error: true
      name: Run echo server
      run: 'git clone https://github.com/wing328/http-echo-server -b openapi-generator-test-server

        (cd http-echo-server && npm install && npm start &)

        '
    - continue-on-error: true
      name: Build
      run: mvn clean package --no-transfer-progress
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/echo_api/java/apache-httpclient
        - samples/client/echo_api/java/feign-gson
        - samples/client/echo_api/java/okhttp-gson
        - samples/client/echo_api/java/resttemplate
        - samples/client/echo_api/java/resteasy
name: Java Client (Echo API) JDK8
on:
  repository_dispatch:
    types: trigger-ga___samples-java-client-echo-api-jdk8.yaml
