jobs:
  tests-dart:
    name: Tests Dart
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        cache-name: pub-cache
      name: Cache test dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('samples/**/pubspec.*')
          }}
        path: $PUB_CACHE
    - continue-on-error: true
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 2.15.0
    - continue-on-error: true
      name: Run tests
      uses: ./.github/actions/run-samples
      with:
        name: samples.dart
name: Samples Dart
on:
  repository_dispatch:
    types: trigger-ga___samples-dart.yaml
