jobs:
  build:
    name: Build .Net projects
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - continue-on-error: true
      name: Build
      run: dotnet build Org.OpenAPITools.sln
      working-directory: ${{ matrix.sample }}
    - continue-on-error: true
      name: Test
      run: dotnet test Org.OpenAPITools.sln
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/petstore/csharp/generichost/net8/AllOf
        - samples/client/petstore/csharp/generichost/net8/AnyOf
        - samples/client/petstore/csharp/generichost/net8/AnyOfNoCompare
        - samples/client/petstore/csharp/generichost/net8/FormModels
        - samples/client/petstore/csharp/generichost/net8/ManualPetstoreTests
        - samples/client/petstore/csharp/generichost/net8/ManualSourceGenerationTests
        - samples/client/petstore/csharp/generichost/net8/NullReferenceTypes
        - samples/client/petstore/csharp/generichost/net8/OneOf
        - samples/client/petstore/csharp/generichost/net8/Petstore
        - samples/client/petstore/csharp/generichost/net8/SourceGeneration
        - samples/client/petstore/csharp/generichost/net8/UseDateTimeForDate
name: Samples C# .Net 8 Clients
on:
  repository_dispatch:
    types: trigger-ga___samples-dotnet.yaml
