jobs:
  build:
    name: Build PHP projects
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: php-cs-fixer, phpunit
    - continue-on-error: true
      name: composer install
      run: composer install
      working-directory: ${{ matrix.sample }}
    - continue-on-error: true
      name: phpunit
      run: vendor/bin/phpunit
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/php-laravel/lib/
name: Samples PHP 7.x
on:
  repository_dispatch:
    types: trigger-ga___samples-php7.yaml
