jobs:
  build:
    name: Build Java Helidon
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2

          '
    - continue-on-error: true
      name: Build
      run: mvn clean package --no-transfer-progress
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/petstore/java-helidon-client/v4/mp
        - samples/server/petstore/java-helidon-server/v4/mp
        version:
        - 21
name: Samples Java Helidon v4
on:
  repository_dispatch:
    types: trigger-ga___samples-java-helidon-v4.yaml
