env:
  GRADLE_VERSION: 6.9
jobs:
  build:
    name: Build Kotlin server
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.gradle

          '
    - continue-on-error: true
      name: Install Gradle wrapper
      uses: eskatos/gradle-command-action@v3
      with:
        arguments: wrapper
        build-root-directory: ${{ matrix.sample }}
        gradle-version: ${{ env.GRADLE_VERSION }}
    - continue-on-error: true
      name: Build
      run: ./gradlew build -x test
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/kotlin-springboot
        - samples/server/petstore/kotlin-springboot-multipart-request-model
        - samples/server/petstore/kotlin-springboot-bigdecimal-default
        - samples/server/petstore/kotlin-springboot-delegate
        - samples/server/petstore/kotlin-springboot-modelMutable
        - samples/server/petstore/kotlin-springboot-reactive
        - samples/server/petstore/kotlin-springboot-source-swagger1
        - samples/server/petstore/kotlin-springboot-source-swagger2
        - samples/server/petstore/kotlin-springboot-springfox
        - samples/server/petstore/kotlin-server/ktor
        - samples/server/petstore/kotlin-server/jaxrs-spec
        - samples/server/petstore/kotlin-server/jaxrs-spec-mutiny
        - samples/server/petstore/kotlin-server-modelMutable
        - samples/server/petstore/kotlin-server/javalin
        - samples/server/others/kotlin-server/jaxrs-spec
        - samples/server/others/kotlin-server/jaxrs-spec-array-response
        - samples/server/petstore/kotlin-spring-cloud
name: Samples Kotlin server
on:
  repository_dispatch:
    types: trigger-ga___samples-kotlin-server.yaml
