jobs:
  build:
    name: Build .Net projects
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 3.1.*
    - continue-on-error: true
      name: Build
      run: dotnet build Org.OpenAPITools.sln
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/petstore/csharp/generichost/standard2.0/Petstore/
        - samples/client/petstore/csharp/httpclient/standard2.0/Petstore/
        - samples/client/petstore/csharp/restsharp/standard2.0/Petstore/
        - samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/
name: Samples C# .Net Standard Client
on:
  repository_dispatch:
    types: trigger-ga___samples-dotnet-standard.yaml
