jobs:
  build:
    name: Build sbt/Scala client, servers
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/build.sbt')
          }}
        path: '~/.ivy2

          '
    - continue-on-error: true
      name: Build and test
      run: sbt -v +test
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/petstore/java/okhttp-gson
        - samples/client/petstore/scalaz
        - samples/client/petstore/scala-pekko
        - samples/server/petstore/scala-lagom-server
        - samples/server/petstore/scala-play-server
        - samples/server/petstore/scala-akka-http-server
        - samples/server/petstore/scala-pekko-http-server
        - samples/server/petstore/scalatra
        - samples/server/petstore/scala-finch
        - samples/server/petstore/scala-http4s-server
        - samples/server/petstore/scala-cask
name: Samples Scala/sbt
on:
  repository_dispatch:
    types: trigger-ga___samples-scala.yaml
