jobs:
  build:
    name: Build Go
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - continue-on-error: true
      run: go version
    - continue-on-error: true
      name: Run test
      run: go test -mod=mod -v
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/go-gin-api-server/
        - samples/server/petstore/go-gin-api-server-interface-only/
name: Samples Go
on:
  repository_dispatch:
    types: trigger-ga___samples-go-gin.yaml
