jobs:
  build:
    name: Build Java Play Framework
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2

          '
    - continue-on-error: true
      name: Build
      run: mvn clean package --no-transfer-progress
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/java-play-framework
        - samples/server/petstore/java-play-framework-api-package-override
        - samples/server/petstore/java-play-framework-async
        - samples/server/petstore/java-play-framework-controller-only
        - samples/server/petstore/java-play-framework-fake-endpoints
        - samples/server/petstore/java-play-framework-fake-endpoints-with-security
        - samples/server/petstore/java-play-framework-no-bean-validation
        - samples/server/petstore/java-play-framework-no-exception-handling
        - samples/server/petstore/java-play-framework-no-interface
        - samples/server/petstore/java-play-framework-no-nullable
        - samples/server/petstore/java-play-framework-no-swagger-ui
        - samples/server/petstore/java-play-framework-no-wrap-calls
name: Samples Java Play Framework
on:
  repository_dispatch:
    types: trigger-ga___samples-java-play-framework.yaml
