jobs:
  build:
    name: Build .Net projects
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build
      run: dotnet build Org.OpenAPITools.sln
      working-directory: ${{ matrix.sample }}
    - continue-on-error: true
      name: Test
      run: dotnet test Org.OpenAPITools.sln
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/client/petstore/csharp/generichost/net4.7/AllOf
        - samples/client/petstore/csharp/generichost/net4.7/AnyOf
        - samples/client/petstore/csharp/generichost/net4.7/AnyOfNoCompare
        - samples/client/petstore/csharp/generichost/net4.7/FormModels
        - samples/client/petstore/csharp/generichost/net4.7/OneOf
        - samples/client/petstore/csharp/generichost/net4.7/Petstore
        - samples/client/petstore/csharp/generichost/net4.7/UseDateTimeForDate
        - samples/client/petstore/csharp/generichost/net4.8/AllOf
        - samples/client/petstore/csharp/generichost/net4.8/AnyOf
        - samples/client/petstore/csharp/generichost/net4.8/AnyOfNoCompare
        - samples/client/petstore/csharp/generichost/net4.8/FormModels
        - samples/client/petstore/csharp/generichost/net4.8/OneOf
        - samples/client/petstore/csharp/generichost/net4.8/Petstore
        - samples/client/petstore/csharp/generichost/net4.8/UseDateTimeForDate
name: Samples C# .Net Framework Clients
on:
  repository_dispatch:
    types: trigger-ga___samples-dotnet-fx.yaml
