jobs:
  build:
    name: Build Java Spring (JDK17)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2

          '
    - continue-on-error: true
      name: Build
      run: mvn clean package --no-transfer-progress
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/openapi3/client/petstore/spring-cloud-3-with-optional
        - samples/openapi3/server/petstore/springboot-3
        - samples/server/petstore/springboot-lombok-data
        - samples/server/petstore/springboot-lombok-tostring
        - samples/server/petstore/springboot-file-delegate-optional
name: Samples Java Spring (JDK17)
on:
  repository_dispatch:
    types: trigger-ga___samples-spring-jdk17.yaml
