jobs:
  build:
    name: Build Kotlin WireMock
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        cache-name: maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.gradle

          '
    - continue-on-error: true
      name: Install Gradle wrapper
      uses: eskatos/gradle-command-action@v3
      with:
        arguments: wrapper
        build-root-directory: ${{ matrix.sample }}
    - continue-on-error: true
      name: Build
      run: ./gradlew build -x test
      working-directory: ${{ matrix.sample }}
    strategy:
      fail-fast: false
      matrix:
        sample:
        - samples/server/petstore/kotlin-wiremock
        - samples/server/echo_api/kotlin-wiremock
name: Samples Kotlin WireMock
on:
  repository_dispatch:
    types: trigger-ga___samples-kotlin-wiremock.yaml
