jobs:
  tests-julia:
    name: Tests Julia
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: julia-actions/setup-julia@v2
      with:
        arch: x64
        version: 1.8
    - continue-on-error: true
      name: Test
      run: 'currdir=`pwd`

        # Using a specific version of OpenAPI.jl helps avoid introducing version inter-dependencies

        #   and allows breaking changes to be done in either repos independently

        # Using develop mode to install package so that it is easier to modify the
        package test files

        julia -e "using Pkg; Pkg.develop(\"OpenAPI\");"

        cd ~/.julia/dev/OpenAPI

        git checkout v0.1.14

        cd $currdir

        rm -rf ~/.julia/dev/OpenAPI/test/client/openapigenerator_petstore_v3/petstore

        rm -rf ~/.julia/dev/OpenAPI/test/server/openapigenerator_petstore_v3/petstore

        cp -r client/petstore/julia ~/.julia/dev/OpenAPI/test/client/openapigenerator_petstore_v3/petstore

        cp -r server/petstore/julia ~/.julia/dev/OpenAPI/test/server/openapigenerator_petstore_v3/petstore

        # setting this env runs only the tests relevant to the openapi-generator repo

        export OPENAPI_GENERATOR=true

        julia -e "using Pkg; Pkg.test(\"OpenAPI\");"

        '
      shell: bash
      working-directory: samples
name: Samples Julia
on:
  repository_dispatch:
    types: trigger-ga___samples-julia.yaml
