jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        cache-name: cache-maven-repository
      name: Cache maven dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2/repository

          ~/.gradle

          !~/.gradle/caches/*/plugin-resolution/

          !~/.m2/repository/org/openapitools/

          '
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          ${{ runner.os }}-build-

          '
    - continue-on-error: true
      name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: ${{ matrix.java }}
        maven-version: 3.8.8
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: Run maven
      run: ./mvnw clean --no-snapshot-updates --batch-mode --quiet install
    - continue-on-error: true
      name: Test Template Retrieval
      run: 'cd modules/openapi-generator-cli/target

        # generator names containing "-" caused problems in the past, see https://github.com/OpenAPITools/openapi-generator/issues/9528

        java -jar ./openapi-generator-cli.jar author template --verbose  -g jaxrs-spec
        --library quarkus

        '
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Gradle tests
      run: 'gradle -b modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
        buildGoSdk --stacktrace

        '
    strategy:
      matrix:
        java:
        - 11
        - 17
name: Windows tests
on:
  repository_dispatch:
    types: trigger-ga___windows.yaml
